### PR TITLE
Add support for OmniHub

### PR DESCRIPTION
**Pull request by Lumute**
Hi, this change is to add support for the OmniHub systems.

These systems do not have any sensor right inside the "backyard" node so an exception is thrown when trying to figure out the unite-of-temperature. But there is a sensor inside the sub-node "body-of-water" so I added a little bit of logic to get it from there...

Tested and now the integration works beautifully in my Home Assistant setup.

### CODE REVIEW

**Comment by Lumute** [comment]
Also, here are my msp config json and telemetry data json in case you want to see the data the API returns for my OmniHub system:

`[{'System': {'Msp-Vsp-Speed-Format': 'Percent', 'Msp-Time-Format': '12 Hour Format', 'Units': 'Standard', 'Msp-Chlor-Display': 'Salt', 'Msp-Language': 'English', 'UI-Display-Mode': 'standard', 'UI-MoodColor-Enabled': 'Yes', 'UI-Heater-SimpleMode': 'Yes', 'UI-Filter-SimpleMode': 'Yes', 'UI-Lights-SimpleMode': 'Yes'}, 'Backyard': {'System-Id': '0', 'Name': 'Backyard', 'Service-Mode-Timeout': '0', 'Body-of-water': {'System-Id': '1', 'Name': 'Pool', 'Type': 'BOW_POOL', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Shared-Priority': 'SHARED_EQUIPMENT_LOW_PRIORITY', 'Shared-Equipment-System-ID': '0', 'Supports-Spillover': 'no', 'Size-In-Gallons': '0', 'Filter': {'System-Id': '2', 'Name': 'Filter Pump', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Filter-Type': 'FMT_VARIABLE_SPEED_PUMP', 'Max-Pump-Speed': '100', 'Min-Pump-Speed': '40', 'Max-Pump-RPM': '3450', 'Min-Pump-RPM': '600', 'Priming-Enabled': 'yes', 'Vsp-Low-Pump-Speed': '70', 'Vsp-Medium-Pump-Speed': '80', 'Vsp-High-Pump-Speed': '90', 'Vsp-Custom-Pump-Speed': '70', 'Freeze-Protect-Override-Interval': '7200'}, 'Sensor': {'System-Id': '3', 'Name': 'WaterSensor', 'Type': 'SENSOR_WATER_TEMP', 'Units': 'UNITS_FAHRENHEIT'}, 'Heater': {'System-Id': '4', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Enabled': 'yes', 'Current-Set-Point': '84', 'CoolingCurrentSetPoint': '70', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'Operation': {'Heater-Equipment': {'System-Id': '5', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_1', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_8HRS', 'Shared-Equipment-System-ID': '-1'}, '#text': 'PEO_HEATER_EQUIPMENT'}}, 'ColorLogic-Light': {'System-Id': '7', 'Name': 'Color Lights', 'Type': 'COLOR_LOGIC_UCL', 'V2-Active': 'no'}, '#text': '01'}, '#text': 'MSP Configuration', 'BOWS': [{'System-Id': '1', 'Name': 'Pool', 'Type': 'BOW_POOL', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Shared-Priority': 'SHARED_EQUIPMENT_LOW_PRIORITY', 'Shared-Equipment-System-ID': '0', 'Supports-Spillover': 'no', 'Size-In-Gallons': '0', 'Filter': {'System-Id': '2', 'Name': 'Filter Pump', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Filter-Type': 'FMT_VARIABLE_SPEED_PUMP', 'Max-Pump-Speed': '100', 'Min-Pump-Speed': '40', 'Max-Pump-RPM': '3450', 'Min-Pump-RPM': '600', 'Priming-Enabled': 'yes', 'Vsp-Low-Pump-Speed': '70', 'Vsp-Medium-Pump-Speed': '80', 'Vsp-High-Pump-Speed': '90', 'Vsp-Custom-Pump-Speed': '70', 'Freeze-Protect-Override-Interval': '7200'}, 'Sensor': {'System-Id': '3', 'Name': 'WaterSensor', 'Type': 'SENSOR_WATER_TEMP', 'Units': 'UNITS_FAHRENHEIT'}, 'Heater': {'System-Id': '4', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Enabled': 'yes', 'Current-Set-Point': '84', 'CoolingCurrentSetPoint': '70', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'Operation': {'Heater-Equipment': {'System-Id': '5', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_1', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_8HRS', 'Shared-Equipment-System-ID': '-1'}, '#text': 'PEO_HEATER_EQUIPMENT'}}, 'ColorLogic-Light': {'System-Id': '7', 'Name': 'Color Lights', 'Type': 'COLOR_LOGIC_UCL'}, '#text': '01', 'Relays': [], 'Lights': [{'System-Id': '7', 'Name': 'Color Lights', 'Type': 'COLOR_LOGIC_UCL', 'V2-Active': 'no'}], 'Heaters': [{'System-Id': '4', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Enabled': 'yes', 'Current-Set-Point': '84', 'CoolingCurrentSetPoint': '70', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'Operation': {'Heater-Equipment': {'System-Id': '5', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_1', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_8HRS', 'Shared-Equipment-System-ID': '-1'}, '#text': 'PEO_HEATER_EQUIPMENT'}}]}]}, 'Schedules': {'sche': [{'bow-system-id': '1', 'equipment-id': '2', 'schedule-system-id': '8', 'event': '164', 'data': '70', 'enabled': '1', 'start-minute': '0', 'start-hour': '8', 'end-minute': '0', 'end-hour': '22', 'days-active': '127', 'recurring': '1'}, {'bow-system-id': '1', 'equipment-id': '2', 'schedule-system-id': '9', 'event': '164', 'data': '40', 'enabled': '1', 'start-minute': '1', 'start-hour': '22', 'end-minute': '59', 'end-hour': '7', 'days-active': '127', 'recurring': '1'}, {'bow-system-id': '1', 'equipment-id': '7', 'schedule-system-id': '10', 'event': '164', 'data': '1', 'enabled': '1', 'start-minute': '0', 'start-hour': '21', 'end-minute': '0', 'end-hour': '23', 'days-active': '127', 'recurring': '1'}]}, 'Favorites': {'Favorite': [{'System-Id': '11', 'Index-Id': '1', 'EquipmentID-Or-ThemeID': '2', 'Sequence': '0', 'Data': '268435440', 'SimpleModeEnabled': '1'}, {'System-Id': '12', 'Index-Id': '2', 'EquipmentID-Or-ThemeID': '4', 'Sequence': '1', 'Data': '0', 'SimpleModeEnabled': '1'}, {'System-Id': '13', 'Index-Id': '3', 'EquipmentID-Or-ThemeID': '7', 'Sequence': '2', 'Data': '1', 'SimpleModeEnabled': '1'}]}, 'MspSystemID': 131xxx, 'BackyardName': 'CasaPanda', 'Relays': []}]`

`{'systemId': '131xxx', 'statusVersion': '7', 'airTemp': '255', 'status': '1', 'state': '1', 'configUpdatedTime': '2022-04-17T16:43:37.997Z', 'datetime': '2022-04-17T13:27:12.617', 'Relays': [], 'BOWS': [{'systemId': '1', 'flow': '255', 'waterTemp': '82', 'Name': 'Pool', 'Supports-Spillover': 'no', 'Filter': {'systemId': '2', 'valvePosition': '1', 'filterSpeed': '80', 'filterState': '1', 'lastSpeed': '80', 'Name': 'Filter Pump', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Filter-Type': 'FMT_VARIABLE_SPEED_PUMP', 'Max-Pump-Speed': '100', 'Min-Pump-Speed': '40', 'Max-Pump-RPM': '3450', 'Min-Pump-RPM': '600', 'Priming-Enabled': 'yes', 'Alarms': []}, 'VirtualHeater': {'systemId': '4', 'Current-Set-Point': '84', 'enable': 'yes'}, 'Heater': {'systemId': '5', 'heaterState': '1', 'enable': 'yes', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Operation': {'VirtualHeater': {'System-Id': '5', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_1', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_8HRS', 'Shared-Equipment-System-ID': '-1', 'Current-Set-Point': '84', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'enable': 'yes', 'systemId': '4'}}, 'Name': 'Heater', 'Alarms': []}, 'CSAD': {'systemId': '0', 'ph': '', 'orp': '', 'status': '0', 'mode': '0', 'Alarms': []}, 'Lights': [{'systemId': '7', 'lightState': '0', 'currentShow': '1', 'Name': 'Color Lights', 'Type': 'COLOR_LOGIC_UCL', 'V2': 'no', 'Alarms': []}], 'Relays': [], 'Pumps': [], 'Heaters': [{'systemId': '5', 'heaterState': '1', 'enable': 'yes', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Operation': {'VirtualHeater': {'System-Id': '5', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_1', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_8HRS', 'Shared-Equipment-System-ID': '-1', 'Current-Set-Point': '84', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'enable': 'yes', 'systemId': '4'}}, 'Name': 'Heater', 'Alarms': []}]}], 'BackyardName': 'CasaPanda', 'Msp-Vsp-Speed-Format': 'Percent', 'Msp-Time-Format': '12 Hour Format', 'Units': 'Standard', 'Msp-Chlor-Display': 'Salt', 'Msp-Language': 'English', 'Unit-of-Measurement': 'Standard', 'Alarms': []}`

**Comment by Lumute** [comment]
Actually, the OmniHub does not have an Air Temperature sensor so the telemetry always has a value of 255 for airTemp which results in an useless sensor. I just cleaned the logic a bit and also added some extra logic to remove the airTemp from the resulting telemetry, that way the sensor in Home Assistant shows as "Unavaliable" which is a bit more accurate instead of showing a temp of 255f / 124c.

**Comment by Lumute** [comment]
> Thanks - will try to review in the coming weeks to get this included. Prioritizing moving the Omnilogic integration to HACS in the short term.

Awesome, thanks! yes I think that is a great move, looks like having it as an official integration is a huge hassle, delaying everything and getting us nowhere, I don't think we have enough installs for them to consider it important...

**Comment by djtimca** [comment]
Thanks - I have added this change as part of a bundle of changes going in to release 0.4.6.

**Pull request closed without merging**
